---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure packages are installed
      apt:
        name: 
          - nginx
          - docker.io
          - docker-compose
          - curl
        update_cache: yes
        
- name: setup webserver
  become: true
  hosts: webserver
  tasks:
    - name: users | adding docker users (for use without sudo)
      user:
        name: "deploy"
        append: yes
        groups: docker
        
    - name: Set authorized key took from file
      authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', './sshkey.pub') }}"

    - name: copy reverse proxy config
      copy:
        src: nginx_frontend.conf
        dest: /etc/nginx/sites-enabled/default
    - name: Restart nginx
      service: name=nginx state=restarted